/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zooapp.view;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import zooapp.controller.ObradaZivotinja;
import zooapp.model.Zivotinja;

/**
 *
 * @author Lorena
 */
public class DjelatniciStatistika extends javax.swing.JFrame {

    /**
     * Creates new form DjelatniciStatistika
     */
    
     private ObradaZivotinja oz;
    private static final long serialVersionUID = 1L;

     public DjelatniciStatistika(List<Zivotinja> zivotinje) {
        super("Graf podaci");
        oz = new ObradaZivotinja();
        setContentPane(createPanel(zivotinje));
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
     }
     
      private ChartPanel createPanel(List<Zivotinja> zivotinje) {
        ChartPanel panel = new ChartPanel(createChart(createDataset(zivotinje)));
        panel.setPreferredSize(new java.awt.Dimension(800, 600));
        return panel;
    }
      
      private JFreeChart createChart(PieDataset dataset) {
        JFreeChart chart = ChartFactory.createPieChart("Broj životinja s kojima rade djelatnici", dataset, true, true, false);
        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setSectionPaint("Djelatnik 1", new Color(255, 100, 100));
        plot.setSectionPaint("Djelatnik 2", new Color(100, 255, 100));
        plot.setSectionPaint("Djelatnik 3", new Color(100, 100, 255));
        plot.setSectionPaint("Djelatnik 4", new Color(255, 255, 100));
        plot.setSectionPaint("Djelatnik 5", new Color(255, 100, 255));
        plot.setSectionPaint("Djelatnik 6", new Color(100, 255, 255));
        return chart;
    }
      
    private PieDataset createDataset(List<Zivotinja> zivotinje) {
        DefaultPieDataset dataset = new DefaultPieDataset();
        Map<String, Integer> counts = new HashMap<>();
        for (Zivotinja zivotinja : zivotinje) {
            String p = zivotinja.getDjelatnik().getIme() + " " + zivotinja.getDjelatnik().getPrezime();
            counts.put(p,counts.getOrDefault(p, 0) + 1);
        }
        for (String p : counts.keySet()) {
             dataset.setValue(p + " (" + counts.get(p) + ")", counts.get(p));
        }
        return dataset;
    }  
      
    
     
    public DjelatniciStatistika() {
        super("Graf podaci");
        oz = new ObradaZivotinja();
        List<Zivotinja> zivBaza = new ArrayList<>(oz.read());
        setContentPane(createPanel(zivBaza));
        pack();
        setLocationRelativeTo(null);
      //  setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
