/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zooapp.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import zooapp.controller.ObradaZivotinja;
import zooapp.model.Djelatnik;
import zooapp.model.Prostorija;
import zooapp.model.Zivotinja;
import zooapp.util.ZooException;

/**
 *
 * @author Lorena
 */
public class ProzorZivotinje extends javax.swing.JFrame {

    private ObradaZivotinja obradaZ = new ObradaZivotinja();
    private ZivotinjaPregled zp;
    private ZivotinjaPromjena zpr;
    

    /**
     * Creates new form ProzorZivotinje
     */
    public ProzorZivotinje() {
        initComponents();
        obradaZ = new ObradaZivotinja();
        // zp = new ZivotinjaPregled();
      //  obradaZ.setEntitet(lstLista.getSelectedValue());
        setTitle("Životinje");
        txtPretraga.requestFocus();

    }

    public ProzorZivotinje(ZivotinjaPregled zp) {
        initComponents();
       // obradaZ = new ObradaZivotinja();
        this.zp = zp;
        setTitle("Životinje");
        txtPretraga.requestFocus();
    }

    public ProzorZivotinje(ZivotinjaPromjena zpr) {
        initComponents();
      //  obradaZ = new ObradaZivotinja();
        this.zpr = zpr;
        setTitle("Životinje");
        txtPretraga.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        jButton1 = new javax.swing.JButton();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList<>();
        btnPretraga = new javax.swing.JButton();
        btnIzmjena = new javax.swing.JButton();
        btnPregled = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();
        btnUnos = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(198, 225, 252));
        jButton1.setText("Povratak na izbornik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPretraga.setBackground(new java.awt.Color(207, 214, 221));
        txtPretraga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });
        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPretragaKeyPressed(evt);
            }
        });

        lstLista.setBackground(new java.awt.Color(207, 214, 221));
        lstLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lstLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstLista);

        btnPretraga.setBackground(new java.awt.Color(198, 225, 252));
        btnPretraga.setText("Pretraga 🔍");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnIzmjena.setBackground(new java.awt.Color(198, 225, 252));
        btnIzmjena.setText("Izmjena ");
        btnIzmjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjenaActionPerformed(evt);
            }
        });

        btnPregled.setBackground(new java.awt.Color(198, 225, 252));
        btnPregled.setText("Pregled");
        btnPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledActionPerformed(evt);
            }
        });

        btnBrisanje.setBackground(new java.awt.Color(198, 225, 252));
        btnBrisanje.setText("Brisanje");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        btnUnos.setBackground(new java.awt.Color(198, 225, 252));
        btnUnos.setText("Unos nove");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(198, 225, 252));
        jButton5.setText("Statistika");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretraga)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnIzmjena, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIzmjena, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ProzorIzbornik().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
    new ZivotinjaUnos(getObradaZ()).setVisible(true);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new ZivotinjeStatistika().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        ucitaj();
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void txtPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ucitaj();
        }
    }//GEN-LAST:event_txtPretragaKeyPressed

    private void btnPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledActionPerformed
        if (lstLista.getSelectedValue() == null || lstLista.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenu životinju!", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        obradaZ.setEntitet(lstLista.getSelectedValue());
        var s = obradaZ.getEntitet();
        // System.out.println(s.getIme());
        LocalDate dR = s.getDatumRodenja().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dD = s.getDatumDolaska().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dS;
        if (s.getDatumSmrti() != null) {
            dS = s.getDatumSmrti().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            dS = null;
        }
        zp = new ZivotinjaPregled(s.getIme(), s.getZivotinjskaVrsta(), s.getVrsta(), s.getDjelatnik(), s.getProstorija(), dR, dD, dS);
        zp.prikazi();

    }//GEN-LAST:event_btnPregledActionPerformed

    private void lstListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaValueChanged
       
    }//GEN-LAST:event_lstListaValueChanged

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        if (lstLista.getSelectedValuesList() == null
                || lstLista.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(getRootPane(),
                    "Prvo odaberite životinju za brisanje!");
            return;
        }

        obradaZ.setEntitet(lstLista.getSelectedValue());

        if (JOptionPane.showConfirmDialog(
                getRootPane(),
                "Želite li sigurno obrisati " + obradaZ.getEntitet().getIme() + " " + "(" + obradaZ.getEntitet().getZivotinjskaVrsta() + ")" + "?",
                "Brisanje",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            obradaZ.delete();
            ucitaj();
        } catch (ZooException ex) {
            JOptionPane.showMessageDialog(
                    getRootPane(),
                    ex.getPoruka());
        }


    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void btnIzmjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjenaActionPerformed
        if (lstLista.getSelectedValue() == null || lstLista.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenu životinju!", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        obradaZ.setEntitet(lstLista.getSelectedValue());
        var s = obradaZ.getEntitet();
        // System.out.println(s.getIme());
        LocalDate dR = s.getDatumRodenja().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dD = s.getDatumDolaska().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dS;
        if (s.getDatumSmrti() != null) {
            dS = s.getDatumSmrti().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            dS = null;
        }
        zpr = new ZivotinjaPromjena(s.getIme(), s.getZivotinjskaVrsta(), s.getVrsta(), s.getDjelatnik(), s.getProstorija(), dR, dD, dS, s.getMinimalnaKvadratura(), s.getMinimalnaKubikaza(), s,getObradaZ());
        zpr.prikazi();

    }//GEN-LAST:event_btnIzmjenaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnIzmjena;
    private javax.swing.JButton btnPregled;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnUnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Zivotinja> lstLista;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void ucitaj() {

        DefaultListModel<Zivotinja> z = new DefaultListModel<>();
        z.addAll(obradaZ.read(txtPretraga.getText()));
        lstLista.setModel(z);
        lstLista.repaint();
    }
    
    

//public void updateList(String ime, String zivotinjskaVrsta, String vrsta, Date datumRodenja, Date datumDolaska, Date datumSmrti, int minimalnaKvadratura, int minimalnaKubikaza, Djelatnik djelatnik, Prostorija prostorija) {
//    obradaZ.setEntitet(lstLista.getSelectedValue());
//    var s = obradaZ.getEntitet();
//    s.setIme(ime);
//    s.setZivotinjskaVrsta(zivotinjskaVrsta);
//    s.setVrsta(vrsta);
//    s.setDatumRodenja(datumRodenja);
//    s.setDatumDolaska(datumDolaska);
//    s.setDatumSmrti(datumSmrti);
//    s.setMinimalnaKvadratura(minimalnaKvadratura);
//    s.setMinimalnaKubikaza(minimalnaKubikaza);
//    s.setDjelatnik(djelatnik);
//    s.setProstorija(prostorija);
//    try {
//            obradaZ.update();
//            lblUspjeh.setText("Životinja uspješno promijenjena!");
//        } catch (ZooException ex) {
//            JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
//        }
//}

    public ObradaZivotinja getObradaZ() {
        return obradaZ;
    }
}
