/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zooapp.view;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import zooapp.controller.ObradaProstorija;
import zooapp.model.Prostorija;
import zooapp.util.ZooException;

/**
 *
 * @author Lorena
 */
public class ProzorProstorije extends javax.swing.JFrame {
    
    private ObradaProstorija obradaP;
    private ProstorijaPregled pp;
    private ProstorijaPromjena pr;

    /**
     * Creates new form ProzorProstorije
     */
    public ProzorProstorije() {
        initComponents();
        obradaP = new ObradaProstorija();
         setTitle("Prostorije");
        txtPretragaP.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPretragaP = new javax.swing.JTextField();
        btnPretragaP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaP = new javax.swing.JList<>();
        btnPregledP = new javax.swing.JButton();
        btnIzmjenaP = new javax.swing.JButton();
        btnUnosP = new javax.swing.JButton();
        btnStatistikaP = new javax.swing.JButton();
        btnBrisanjeP = new javax.swing.JButton();
        btnIzbornik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPretragaP.setBackground(new java.awt.Color(207, 214, 221));
        txtPretragaP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPretragaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaPActionPerformed(evt);
            }
        });
        txtPretragaP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPretragaPKeyPressed(evt);
            }
        });

        btnPretragaP.setBackground(new java.awt.Color(198, 225, 252));
        btnPretragaP.setText("Pretraga 🔍");
        btnPretragaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaPActionPerformed(evt);
            }
        });

        lstListaP.setBackground(new java.awt.Color(207, 214, 221));
        lstListaP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstListaP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lstListaP.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListaPValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstListaP);

        btnPregledP.setBackground(new java.awt.Color(198, 225, 252));
        btnPregledP.setText("Pregled");
        btnPregledP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledPActionPerformed(evt);
            }
        });

        btnIzmjenaP.setBackground(new java.awt.Color(198, 225, 252));
        btnIzmjenaP.setText("Izmjena ");
        btnIzmjenaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjenaPActionPerformed(evt);
            }
        });

        btnUnosP.setBackground(new java.awt.Color(198, 225, 252));
        btnUnosP.setText("Unos");
        btnUnosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosPActionPerformed(evt);
            }
        });

        btnStatistikaP.setBackground(new java.awt.Color(198, 225, 252));
        btnStatistikaP.setText("Statistika");
        btnStatistikaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikaPActionPerformed(evt);
            }
        });

        btnBrisanjeP.setBackground(new java.awt.Color(198, 225, 252));
        btnBrisanjeP.setText("Brisanje");
        btnBrisanjeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjePActionPerformed(evt);
            }
        });

        btnIzbornik.setBackground(new java.awt.Color(198, 225, 252));
        btnIzbornik.setText("Povratak na izbornik");
        btnIzbornik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbornikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPretragaP, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretragaP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPregledP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnIzmjenaP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(btnUnosP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnStatistikaP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnBrisanjeP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzbornik)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretragaP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretragaP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPregledP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmjenaP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnosP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStatistikaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrisanjeP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnIzbornik)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaPActionPerformed

    private void txtPretragaPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaPKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ucitajProstorije();
        }
    }//GEN-LAST:event_txtPretragaPKeyPressed

    private void btnPretragaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaPActionPerformed
         ucitajProstorije();
    }//GEN-LAST:event_btnPretragaPActionPerformed

    private void lstListaPValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaPValueChanged
         if(evt.getValueIsAdjusting()){
            return;
        }
        if(lstListaP.getSelectedValue()==null){
            return;
        }
    }//GEN-LAST:event_lstListaPValueChanged

    private void btnPregledPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledPActionPerformed
        if(lstListaP.getSelectedValue() == null || lstListaP.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenu prostoriju!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        obradaP.setEntitet(lstListaP.getSelectedValue());
        var s = obradaP.getEntitet();
        pp = new ProstorijaPregled(obradaP.getEntitet().getNaziv(),obradaP.getEntitet().getSirina(),obradaP.getEntitet().getDuzina(),obradaP.getEntitet().getVisina());
        pp.prikazi();
    }//GEN-LAST:event_btnPregledPActionPerformed

    private void btnUnosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosPActionPerformed
        new ProstorijaUnos().setVisible(true);
    }//GEN-LAST:event_btnUnosPActionPerformed

    private void btnStatistikaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikaPActionPerformed
        new ProstorijeStatistika().setVisible(true);
    }//GEN-LAST:event_btnStatistikaPActionPerformed

    private void btnBrisanjePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjePActionPerformed
        if(lstListaP.getSelectedValuesList()==null
            || lstListaP.getSelectedValuesList().isEmpty()){
            JOptionPane.showMessageDialog(getRootPane(),
                "Prvo odaberite prostoriju za brisanje!");
            return;
        }

        obradaP.setEntitet(lstListaP.getSelectedValue());

        if(JOptionPane.showConfirmDialog(
            getRootPane(),
            "Želite li sigurno obrisati " + obradaP.getEntitet().getNaziv() + " ?",
            "Brisanje",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE)==JOptionPane.NO_OPTION){
        return;
        }

        try {
            obradaP.delete();
            //ucitaj();
        } catch (ZooException ex) {
            JOptionPane.showMessageDialog(
                getRootPane(),
                ex.getPoruka());
        }
    }//GEN-LAST:event_btnBrisanjePActionPerformed

    private void btnIzbornikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbornikActionPerformed
        new ProzorIzbornik().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIzbornikActionPerformed

    private void btnIzmjenaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjenaPActionPerformed
        if(lstListaP.getSelectedValue() == null || lstListaP.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenu prostoriju!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        obradaP.setEntitet(lstListaP.getSelectedValue());
        var s = obradaP.getEntitet();
        pr = new ProstorijaPromjena(s.getNaziv(), s.getSirina(), s.getDuzina(), s.getVisina(),s);
        pr.prikazi();
        
    }//GEN-LAST:event_btnIzmjenaPActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanjeP;
    private javax.swing.JButton btnIzbornik;
    private javax.swing.JButton btnIzmjenaP;
    private javax.swing.JButton btnPregledP;
    private javax.swing.JButton btnPretragaP;
    private javax.swing.JButton btnStatistikaP;
    private javax.swing.JButton btnUnosP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Prostorija> lstListaP;
    private javax.swing.JTextField txtPretragaP;
    // End of variables declaration//GEN-END:variables

    private void ucitajProstorije() {
         DefaultListModel<Prostorija> p = new DefaultListModel<>();
        p.addAll(obradaP.read(txtPretragaP.getText()));
        lstListaP.setModel(p);
        lstListaP.repaint();

    }
}
