/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zooapp.view;

import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import zooapp.controller.ObradaZivotinja;
import zooapp.model.Zivotinja;

/**
 *
 * @author Lorena
 */
public class ZivotinjaPregled extends javax.swing.JFrame {

    private ObradaZivotinja obradaZ;

    /**
     * Creates new form zivotinjaPregled
     */
    public ZivotinjaPregled() {
        initComponents();
        obradaZ = new ObradaZivotinja();
        lblPR.setVisible(false);
        lblDJ.setVisible(false);
        lblSM.setVisible(false);
    }
    
     public ZivotinjaPregled(String ime, String zivotinjskaVrsta,String vrsta) {
        initComponents();
        obradaZ = new ObradaZivotinja();
        lblPR.setVisible(false);
        lblDJ.setVisible(false);
        lblSM.setVisible(false);
        napuniView(ime,zivotinjskaVrsta,vrsta);
    }
   
    public void napuniView(String ime, String zivotinjskaVrsta,String vrsta) {
     //  System.out.println(ime + " iz viewa");
       lblName.setText(ime.toUpperCase());
       lblZivVrsta.setText(zivotinjskaVrsta.toUpperCase());
       lblVrsta.setText(vrsta.toUpperCase());
    }
    
    public void prikazi() {
        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnViseInfo = new javax.swing.JButton();
        lblPR = new javax.swing.JLabel();
        lblDJ = new javax.swing.JLabel();
        lblSM = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblZivVrsta = new javax.swing.JLabel();
        lblVrsta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("IME:");

        jLabel3.setText("ŽIVOTINJSKA VRSTA:");

        jLabel4.setText("VRSTA:");

        jLabel5.setText("DATUM ROĐENJA:");

        jLabel6.setText("DATUM DOLASKA:");

        btnViseInfo.setBackground(new java.awt.Color(198, 225, 252));
        btnViseInfo.setText("Više informacija");
        btnViseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViseInfoActionPerformed(evt);
            }
        });

        lblPR.setText("PROSTORIJA:");

        lblDJ.setText("DJELATNIK:");

        lblSM.setText("DATUM SMRTI:");

        lblName.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 51, 255));

        lblZivVrsta.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        lblZivVrsta.setForeground(new java.awt.Color(51, 51, 255));

        lblVrsta.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        lblVrsta.setForeground(new java.awt.Color(21, 21, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDJ)
                            .addComponent(lblSM))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblZivVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(btnViseInfo)
                            .addComponent(lblPR))
                        .addGap(206, 206, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblZivVrsta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblVrsta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addComponent(btnViseInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSM)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViseInfoActionPerformed
        lblPR.setVisible(true);
        lblDJ.setVisible(true);
        lblSM.setVisible(true);
    }//GEN-LAST:event_btnViseInfoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViseInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDJ;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPR;
    private javax.swing.JLabel lblSM;
    private javax.swing.JLabel lblVrsta;
    private javax.swing.JLabel lblZivVrsta;
    // End of variables declaration//GEN-END:variables
}
